import {render,screen} from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import {describe,expect,it,vi} from "vitest";
import type {Client} from "@/src/features/clients";
import type {Project} from "@/src/features/projects";
import {ClientProjectTree} from "../client-project-tree";

const client=(id:string,name:string,industry:string|null=null):Client=>({id,name,industry,description:null,targetAudience:null,brandVoice:null,websiteUrl:null,instagramUrl:null,facebookUrl:null,businessObjectives:null,status:"ACTIVE",createdById:"u1",createdBy:{id:"u1",name:"User",username:"user",email:"u@test.com"},createdAt:"2026-07-01T00:00:00Z",updatedAt:"2026-07-01T00:00:00Z"});
const project=(id:string,clientId:string,title:string):Project=>({id,clientId,title,projectType:null,growthObjective:null,platforms:[],startDate:null,endDate:null,status:"ACTIVE",month:8,year:2026,assignedUserId:null,contentTarget:null,createdAt:"2026-07-01T00:00:00Z",updatedAt:"2026-07-01T00:00:00Z"});
const clients=[client("c1","BigU Foods","Hospitality"),client("c2","Salon Spot","Beauty")];
const projects=[project("p1","c1","August Growth Plan"),project("p2","c1","Diwali Campaign")];

describe("ClientProjectTree",()=>{
 it("renders client rows and separate navigation links",()=>{render(<ClientProjectTree clients={clients} projects={projects} pathname="/dashboard"/>);expect(screen.getByRole("link",{name:/BigU Foods/})).toHaveAttribute("href","/clients/c1");expect(screen.getByRole("button",{name:"Expand BigU Foods"})).toBeInTheDocument()});
 it("expands and collapses projects with mouse and keyboard",async()=>{const user=userEvent.setup();render(<ClientProjectTree clients={clients} projects={projects} pathname="/dashboard"/>);const toggle=screen.getByRole("button",{name:"Expand BigU Foods"});expect(toggle).toHaveAttribute("aria-expanded","false");await user.click(toggle);expect(screen.getByRole("link",{name:/August Growth Plan/})).toHaveAttribute("href","/projects/p1");expect(toggle).toHaveAttribute("aria-expanded","true");toggle.focus();await user.keyboard("{Enter}");expect(toggle).toHaveAttribute("aria-expanded","false")});
 it("marks active routes and expands an active project's parent",()=>{render(<ClientProjectTree clients={clients} projects={projects} pathname="/projects/p2"/>);expect(screen.getByRole("link",{name:/Diwali Campaign/})).toHaveAttribute("aria-current","page");expect(screen.getByRole("button",{name:"Collapse BigU Foods"})).toHaveAttribute("aria-expanded","true")});
 it("marks an active client",()=>{render(<ClientProjectTree clients={clients} projects={projects} pathname="/clients/c2"/>);expect(screen.getByRole("link",{name:/Salon Spot/})).toHaveAttribute("aria-current","page")});
 it("searches clients, industries, and project titles",()=>{const {rerender}=render(<ClientProjectTree clients={clients} projects={projects} pathname="/" search="Diwali"/>);expect(screen.getByText("Diwali Campaign")).toBeInTheDocument();expect(screen.queryByText("Salon Spot")).not.toBeInTheDocument();rerender(<ClientProjectTree clients={clients} projects={projects} pathname="/" search="Beauty"/>);expect(screen.getByText("Salon Spot")).toBeInTheDocument()});
 it("shows empty client and empty project states",async()=>{const user=userEvent.setup();const {rerender}=render(<ClientProjectTree clients={[]} projects={[]} pathname="/"/>);expect(screen.getByText("No clients yet")).toBeInTheDocument();rerender(<ClientProjectTree clients={[clients[1]]} projects={[]} pathname="/"/>);await user.click(screen.getByRole("button",{name:"Expand Salon Spot"}));expect(screen.getByText("No projects yet")).toBeInTheDocument();expect(screen.getByRole("link",{name:/Create project/})).toHaveAttribute("href","/projects/new?clientId=c2")});
 it("shows tree loading and per-client project errors",async()=>{const user=userEvent.setup();const {rerender}=render(<ClientProjectTree clients={[]} projects={[]} pathname="/" isLoading/>);expect(screen.getByLabelText("Loading clients and projects")).toBeInTheDocument();rerender(<ClientProjectTree clients={clients} projects={[]} pathname="/" projectsError={new Error("no")}/>);await user.click(screen.getByRole("button",{name:"Expand BigU Foods"}));expect(screen.getAllByText(/Could not load projects/)).toHaveLength(2)});
 it("calls the mobile close callback on navigation",async()=>{const user=userEvent.setup(),onNavigate=vi.fn();render(<ClientProjectTree clients={clients} projects={projects} pathname="/" onNavigate={onNavigate}/>);await user.click(screen.getByRole("link",{name:/BigU Foods/}));expect(onNavigate).toHaveBeenCalled()});
});
